The macro AC_TEST_PROGRAM was deprecated and replaced with another macro, which itself was deprecated and replaced with AC_RUN_IFELSE. I've substituted the three instances here and added a third argument, the "action-if-false," or what it should do if the test fails.
For each, this third argument is just an AC_MSG_NOTICE informing
the user that the test failed... but from the data I'm seeing across
four different systems -- three flavors of Linux and one Darwin -- one
test won't compile at all, and another always returns 1. 

For SELECT_WORKS_ON_FIFO it has something to do with the expansion of
one of the macros in the mini-test program; the errors are:

selectworksonfifostest.c: In function ‘main’:
selectworksonfifostest.c:20:19: error: expected expression before ‘do’
selectworksonfifostest.c:23:19: error: expected expression before ‘do’

FSTAT_WORKS_ON_FIFO just returns 1. POLL_WORKS_ON_FIFO seems to return
0 pretty consistently across systems.

I guess what I'm driving at here is using FIFOs is probably something
that can be safely dropped from the project altogether, along with
NP_LOCAL as an option in options.h.